apiVersion: v1
kind: Service
metadata:
  name: word-to-pdf
  labels:
    app: word-to-pdf
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: word-to-pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-to-pdf
  labels:
    app: word-to-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-to-pdf
  template:
    metadata:
      labels:
        app: word-to-pdf
    spec:
      containers:
        - name: word-to-pdf
          image: "patrickkoss/word-to-pdf:0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: word-to-pdf-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - example.com
    secretName: word-to-pdf-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: word-to-pdf
            port:
              number: 5000
