version: "3.5"
services:
  wordtopdf:
    container_name: wordtopdf
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  nginx:
    image: nginx:1.21.0
    container_name: nginx
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443